<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComparedProductDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('compared_product_details')->truncate();
        DB::table('compared_product_details')->insert([
            ['id' => 1,'compared_id' =>1, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>15001,'str_value' =>'','unit' =>'円','remarks' => 'クーポン使用可能商品1'],
            ['id' => 2,'compared_id' =>2, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>26,'str_value' =>'','unit' =>'kg','remarks' => '設置補助可能1'],
            ['id' => 3,'compared_id' =>3, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>11,'str_value' =>'','unit' =>'年','remarks' => '買い替え割有り1！'],
            ['id' => 4,'compared_id' =>4, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>3,'int_value' =>0,'str_value' =>'','unit' =>'','remarks' => '保証書を提示で無償交換1！'],
            ['id' => 5,'compared_id' =>5, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => '開ける頻度が多くてもすぐ冷却1'],
            ['id' => 6,'compared_id' =>1, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>15002,'str_value' =>'','unit' =>'円','remarks' => 'クーポン使用可能商品2'],
            ['id' => 7,'compared_id' =>2, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>27,'str_value' =>'','unit' =>'kg','remarks' => '設置補助可能2'],
            ['id' => 8,'compared_id' =>3, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>12,'str_value' =>'','unit' =>'年','remarks' => '買い替え割有り2！'],
            ['id' => 9,'compared_id' =>4, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>3,'int_value' =>1,'str_value' =>'','unit' =>'','remarks' => '保証書を提示で無償交換2！'],
            ['id' => 10,'compared_id' =>5, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '開ける頻度が多くてもすぐ冷却2'],
            ['id' => 11,'compared_id' =>1, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>15003,'str_value' =>'','unit' =>'円','remarks' => 'クーポン使用可能商品3'],
            ['id' => 12,'compared_id' =>2, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>28,'str_value' =>'','unit' =>'kg','remarks' => '設置補助可能3'],
            ['id' => 13,'compared_id' =>3, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>14,'str_value' =>'','unit' =>'年','remarks' => '買い替え割有り3！'],
            ['id' => 14,'compared_id' =>4, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>3,'int_value' =>0,'str_value' =>'','unit' =>'','remarks' => '保証書を提示で無償交換3！'],
            ['id' => 15,'compared_id' =>5, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>2,'int_value' =>0,'str_value' =>'低い','unit' =>'','remarks' => '開ける頻度が多くてもすぐ冷却3'],
            ['id' => 16,'compared_id' =>1, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>15004,'str_value' =>'','unit' =>'円','remarks' => 'クーポン使用可能商品4'],
            ['id' => 17,'compared_id' =>2, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>29,'str_value' =>'','unit' =>'kg','remarks' => '設置補助可能4'],
            ['id' => 18,'compared_id' =>3, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>15,'str_value' =>'','unit' =>'年','remarks' => '買い替え割有り4！'],
            ['id' => 19,'compared_id' =>4, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>3,'int_value' =>1,'str_value' =>'','unit' =>'','remarks' => '保証書を提示で無償交換4！'],
            ['id' => 20,'compared_id' =>5, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => '開ける頻度が多くてもすぐ冷却4'],
            ['id' => 21,'compared_id' =>1, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>15005,'str_value' =>'','unit' =>'円','remarks' => 'クーポン使用可能商品5'],
            ['id' => 22,'compared_id' =>2, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>30,'str_value' =>'','unit' =>'kg','remarks' => '設置補助可能5'],
            ['id' => 23,'compared_id' =>3, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>1,'int_value' =>16,'str_value' =>'','unit' =>'年','remarks' => '買い替え割有り5！'],
            ['id' => 24,'compared_id' =>4, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>3,'int_value' =>0,'str_value' =>'','unit' =>'','remarks' => '保証書を提示で無償交換5！'],
            ['id' => 25,'compared_id' =>5, 'company_id' => 1, 'comparison_criteria_id' =>1, 'type' =>2,'int_value' =>0,'str_value' =>'低い','unit' =>'','remarks' => '開ける頻度が多くてもすぐ冷却5'],
            ['id' => 26,'compared_id' =>6, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>5001,'str_value' =>'','unit' =>'円','remarks' => '業界最安値！1'],
            ['id' => 27,'compared_id' =>7, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => '備考1'],
            ['id' => 28,'compared_id' =>8, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>1501,'str_value' =>'','unit' =>'ml','remarks' => '備考1'],
            ['id' => 29,'compared_id' =>9, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>70,'str_value' =>'','unit' =>'%','remarks' => '備考1'],
            ['id' => 30,'compared_id' =>10, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>80,'str_value' =>'','unit' =>'%','remarks' => '備考1'],
            ['id' => 31,'compared_id' =>6, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>5002,'str_value' =>'','unit' =>'円','remarks' => '備考業界最安値！2'],
            ['id' => 32,'compared_id' =>7, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>2,'int_value' =>0,'str_value' =>'低い','unit' =>'','remarks' => '備考2'],
            ['id' => 33,'compared_id' =>8, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>1502,'str_value' =>'','unit' =>'ml','remarks' => '備考2'],
            ['id' => 34,'compared_id' =>9, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>60,'str_value' =>'','unit' =>'%','remarks' => '備考2'],
            ['id' => 35,'compared_id' =>10, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>70,'str_value' =>'','unit' =>'%','remarks' => '備考2'],
            ['id' => 36,'compared_id' =>6, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>5003,'str_value' =>'','unit' =>'円','remarks' => '備考業界最安値！3'],
            ['id' => 37,'compared_id' =>7, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>2,'int_value' =>0,'str_value' =>'やや低い','unit' =>'','remarks' => '備考3'],
            ['id' => 38,'compared_id' =>8, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>1503,'str_value' =>'','unit' =>'ml','remarks' => '備考3'],
            ['id' => 39,'compared_id' =>9, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>50,'str_value' =>'','unit' =>'%','remarks' => '備考3'],
            ['id' => 40,'compared_id' =>10, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>60,'str_value' =>'','unit' =>'%','remarks' => '備考3'],
            ['id' => 41,'compared_id' =>6, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>5004,'str_value' =>'','unit' =>'円','remarks' => '備考業界最安値！4'],
            ['id' => 42,'compared_id' =>7, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '備考4'],
            ['id' => 43,'compared_id' =>8, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>1504,'str_value' =>'','unit' =>'ml','remarks' => '備考4'],
            ['id' => 44,'compared_id' =>9, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>40,'str_value' =>'','unit' =>'%','remarks' => '備考4'],
            ['id' => 45,'compared_id' =>10, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>50,'str_value' =>'','unit' =>'%','remarks' => '備考4'],
            ['id' => 46,'compared_id' =>6, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>5006,'str_value' =>'','unit' =>'円','remarks' => '備考業界最安値！5'],
            ['id' => 47,'compared_id' =>7, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>2,'int_value' =>0,'str_value' =>'低い','unit' =>'','remarks' => '備考5'],
            ['id' => 48,'compared_id' =>8, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>1,'int_value' =>1505,'str_value' =>'','unit' =>'ml','remarks' => '備考5'],
            ['id' => 49,'compared_id' =>9, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>30,'str_value' =>'','unit' =>'%','remarks' => '備考5'],
            ['id' => 50,'compared_id' =>10, 'company_id' => 1, 'comparison_criteria_id' =>2, 'type' =>4,'int_value' =>40,'str_value' =>'','unit' =>'%','remarks' => '備考5'],
            ['id' => 51,'compared_id' =>11, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>2500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 52,'compared_id' =>12, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>0,'str_value' =>'一般的','unit' =>'','remarks' => ''],
            ['id' => 53,'compared_id' =>13, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>4,'int_value' =>70,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 54,'compared_id' =>11, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>2500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 55,'compared_id' =>12, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>0,'str_value' =>'一般的','unit' =>'','remarks' => ''],
            ['id' => 56,'compared_id' =>13, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>4,'int_value' =>70,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 57,'compared_id' =>11, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>2500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 58,'compared_id' =>12, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>0,'str_value' =>'一般的','unit' =>'','remarks' => ''],
            ['id' => 59,'compared_id' =>13, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>4,'int_value' =>70,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 60,'compared_id' =>11, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>2500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 61,'compared_id' =>12, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>0,'str_value' =>'一般的','unit' =>'','remarks' => ''],
            ['id' => 62,'compared_id' =>13, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>4,'int_value' =>70,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 63,'compared_id' =>11, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>2500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 64,'compared_id' =>12, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>1,'int_value' =>0,'str_value' =>'一般的','unit' =>'','remarks' => ''],
            ['id' => 65,'compared_id' =>13, 'company_id' => 1, 'comparison_criteria_id' =>3, 'type' =>4,'int_value' =>70,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 66,'compared_id' =>14, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>3500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 67,'compared_id' =>15, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => ''],
            ['id' => 68,'compared_id' =>16, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>800,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 69,'compared_id' =>17, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>60,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 70,'compared_id' =>18, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>80,'str_value' =>'','unit' =>'%','remarks' => ''],            
            ['id' => 71,'compared_id' =>14, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>3500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 72,'compared_id' =>15, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => ''],
            ['id' => 73,'compared_id' =>16, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>800,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 74,'compared_id' =>17, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>60,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 75,'compared_id' =>18, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>80,'str_value' =>'','unit' =>'%','remarks' => ''],            
            ['id' => 76,'compared_id' =>14, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>3500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 77,'compared_id' =>15, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => ''],
            ['id' => 78,'compared_id' =>16, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>800,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 79,'compared_id' =>17, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>60,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 80,'compared_id' =>18, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>80,'str_value' =>'','unit' =>'%','remarks' => ''],            
            ['id' => 81,'compared_id' =>14, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>3500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 82,'compared_id' =>15, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => ''],
            ['id' => 83,'compared_id' =>16, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>800,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 84,'compared_id' =>17, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>60,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 85,'compared_id' =>18, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>80,'str_value' =>'','unit' =>'%','remarks' => ''],            
            ['id' => 86,'compared_id' =>14, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>3500,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 87,'compared_id' =>15, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>2,'int_value' =>0,'str_value' =>'やや高い','unit' =>'','remarks' => ''],
            ['id' => 88,'compared_id' =>16, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>1,'int_value' =>800,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 89,'compared_id' =>17, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>60,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 90,'compared_id' =>18, 'company_id' => 1, 'comparison_criteria_id' =>4, 'type' =>4,'int_value' =>80,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 91,'compared_id' =>19, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>50000,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 92,'compared_id' =>20, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>15,'str_value' =>'','unit' =>'Kg','remarks' => ''],
            ['id' => 93,'compared_id' =>19, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>50000,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 94,'compared_id' =>20, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>15,'str_value' =>'','unit' =>'Kg','remarks' => ''],
            ['id' => 95,'compared_id' =>19, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>50000,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 96,'compared_id' =>20, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>15,'str_value' =>'','unit' =>'Kg','remarks' => ''],
            ['id' => 97,'compared_id' =>19, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>50000,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 98,'compared_id' =>20, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>15,'str_value' =>'','unit' =>'Kg','remarks' => ''],
            ['id' => 99,'compared_id' =>19, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>50000,'str_value' =>'','unit' =>'円','remarks' => ''],
            ['id' => 100,'compared_id' =>20, 'company_id' => 1, 'comparison_criteria_id' =>5, 'type' =>1,'int_value' =>15,'str_value' =>'','unit' =>'Kg','remarks' => ''],
            ['id' => 101,'compared_id' =>21, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>6500,'str_value' =>'','unit' =>'円','remarks' => '他社より安くします！'],
            ['id' => 102,'compared_id' =>22, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>5,'str_value' =>'','unit' =>'年','remarks' => '5年間は必ずふわふわ'],
            ['id' => 103,'compared_id' =>23, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>4,'int_value' =>90,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 104,'compared_id' =>21, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>6500,'str_value' =>'','unit' =>'円','remarks' => '他社より安くします！'],
            ['id' => 105,'compared_id' =>22, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>5,'str_value' =>'','unit' =>'年','remarks' => '5年間は必ずふわふわ'],
            ['id' => 106,'compared_id' =>23, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>4,'int_value' =>90,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 107,'compared_id' =>21, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>6500,'str_value' =>'','unit' =>'円','remarks' => '他社より安くします！'],
            ['id' => 108,'compared_id' =>22, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>5,'str_value' =>'','unit' =>'年','remarks' => '5年間は必ずふわふわ'],
            ['id' => 109,'compared_id' =>23, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>4,'int_value' =>90,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 110,'compared_id' =>21, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>6500,'str_value' =>'','unit' =>'円','remarks' => '他社より安くします！'],
            ['id' => 111,'compared_id' =>22, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>5,'str_value' =>'','unit' =>'年','remarks' => '5年間は必ずふわふわ'],
            ['id' => 112,'compared_id' =>23, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>4,'int_value' =>90,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 113,'compared_id' =>21, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>6500,'str_value' =>'','unit' =>'円','remarks' => '他社より安くします！'],
            ['id' => 114,'compared_id' =>22, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>5,'str_value' =>'','unit' =>'年','remarks' => '5年間は必ずふわふわ'],
            ['id' => 115,'compared_id' =>23, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>4,'int_value' =>90,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 116,'compared_id' =>21, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>6500,'str_value' =>'','unit' =>'円','remarks' => '他社より安くします！'],
            ['id' => 117,'compared_id' =>22, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>1,'int_value' =>5,'str_value' =>'','unit' =>'年','remarks' => '5年間は必ずふわふわ'],
            ['id' => 118,'compared_id' =>23, 'company_id' => 1, 'comparison_criteria_id' =>6, 'type' =>4,'int_value' =>90,'str_value' =>'','unit' =>'%','remarks' => ''],
            ['id' => 119,'compared_id' =>24, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>5500,'str_value' =>'','unit' =>'円','remarks' => '二つ購入で一割引き'],
            ['id' => 120,'compared_id' =>25, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '6時間キンキンを維持！'],
            ['id' => 121,'compared_id' =>26, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>1000,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 122,'compared_id' =>24, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>5500,'str_value' =>'','unit' =>'円','remarks' => '二つ購入で一割引き'],
            ['id' => 123,'compared_id' =>25, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '6時間キンキンを維持！'],
            ['id' => 124,'compared_id' =>26, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>1000,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 125,'compared_id' =>24, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>5500,'str_value' =>'','unit' =>'円','remarks' => '二つ購入で一割引き'],
            ['id' => 126,'compared_id' =>25, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '6時間キンキンを維持！'],
            ['id' => 127,'compared_id' =>26, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>1000,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 128,'compared_id' =>24, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>5500,'str_value' =>'','unit' =>'円','remarks' => '二つ購入で一割引き'],
            ['id' => 129,'compared_id' =>25, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '6時間キンキンを維持！'],
            ['id' => 130,'compared_id' =>26, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>1000,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 131,'compared_id' =>24, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>5500,'str_value' =>'','unit' =>'円','remarks' => '二つ購入で一割引き'],
            ['id' => 132,'compared_id' =>25, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '6時間キンキンを維持！'],
            ['id' => 133,'compared_id' =>26, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>1000,'str_value' =>'','unit' =>'ml','remarks' => ''],
            ['id' => 134,'compared_id' =>24, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>5500,'str_value' =>'','unit' =>'円','remarks' => '二つ購入で一割引き'],
            ['id' => 135,'compared_id' =>25, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>2,'int_value' =>0,'str_value' =>'高い','unit' =>'','remarks' => '6時間キンキンを維持！'],
            ['id' => 136,'compared_id' =>26, 'company_id' => 1, 'comparison_criteria_id' =>7, 'type' =>1,'int_value' =>1000,'str_value' =>'','unit' =>'ml','remarks' => ''],
        ]);
    }
}
